In [1]:
import numpy as np
import pandas as pn

In [2]:
data = pn.read_csv("Housing.csv")
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [3]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [4]:
old_data = data.copy()

In [5]:
new_data = pn.get_dummies(data)
new_data

,price,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,0,1,1,0,...,0,1,0,0,1,0,1,1,0,0
1,12250000,8960,4,4,4,3,0,1,1,0,...,0,1,0,0,1,1,0,1,0,0
2,12250000,9960,3,2,2,2,0,1,1,0,...,1,1,0,1,0,0,1,0,1,0
3,12215000,7500,4,2,2,3,0,1,1,0,...,1,1,0,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,0,1,0,1,...,1,1,0,0,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,0,1,1,0,...,1,1,0,1,0,1,0,0,0,1
541,1767150,2400,3,1,1,0,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
542,1750000,3620,2,1,1,0,0,1,1,0,...,0,1,0,1,0,1,0,0,0,1
543,1750000,2910,3,1,1,0,1,0,1,0,...,0,1,0,1,0,1,0,1,0,0
544,1750000,3850,3,1,2,0,0,1,1,0,...,0,1,0,1,0,1,0,0,0,1

In [6]:
new_data['price'].describe().astype(int)

count         545
mean      4766729
std       1870439
min       1750000
25%       3430000
50%       4340000
75%       5740000
max      13300000
Name: price, dtype: int32

In [7]:
new_data['new_price'] = np.where(new_data['price']<=3430000,'C1',
                                 np.where(new_data['price']<=4340000,'C2',
                                 np.where(new_data['price']<=5740000,'C3','C4')))

In [8]:
new_data

,price,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,new_price
0,13300000,7420,4,2,3,2,0,1,1,0,...,1,0,0,1,0,1,1,0,0,C4
1,12250000,8960,4,4,4,3,0,1,1,0,...,1,0,0,1,1,0,1,0,0,C4
2,12250000,9960,3,2,2,2,0,1,1,0,...,1,0,1,0,0,1,0,1,0,C4
3,12215000,7500,4,2,2,3,0,1,1,0,...,1,0,0,1,0,1,1,0,0,C4
4,11410000,7420,4,1,2,2,0,1,0,1,...,1,0,0,1,1,0,1,0,0,C4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,0,1,1,0,...,1,0,1,0,1,0,0,0,1,C1
541,1767150,2400,3,1,1,0,1,0,1,0,...,1,0,1,0,1,0,0,1,0,C1
542,1750000,3620,2,1,1,0,0,1,1,0,...,1,0,1,0,1,0,0,0,1,C1
543,1750000,2910,3,1,1,0,1,0,1,0,...,1,0,1,0,1,0,1,0,0,C1
544,1750000,3850,3,1,2,0,0,1,1,0,...,1,0,1,0,1,0,0,0,1,C1

In [9]:
new_data.drop(['price'],axis=1,inplace=True)

In [10]:
new_data.corr()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_7328\594412850.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  new_data.corr()

,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
area,1.000000,0.151858,0.193820,0.083996,0.352980,-0.288874,0.288874,-0.140297,0.140297,-0.047417,0.047417,0.009229,-0.009229,-0.222393,0.222393,-0.234779,0.234779,0.145772,0.006156,-0.142278
bedrooms,0.151858,1.000000,0.373930,0.408564,0.139270,0.012033,-0.012033,-0.080549,0.080549,-0.097312,0.097312,-0.046049,0.046049,-0.160603,0.160603,-0.079023,0.079023,0.079054,0.050040,-0.126252
bathrooms,0.193820,0.373930,1.000000,0.326165,0.177496,-0.042398,0.042398,-0.126469,0.126469,-0.102106,0.102106,-0.067159,0.067159,-0.186915,0.186915,-0.063472,0.063472,0.108139,0.029834,-0.132107
stories,0.083996,0.408564,0.326165,1.000000,0.045547,-0.121706,0.121706,-0.043538,0.043538,0.172394,-0.172394,-0.018847,0.018847,-0.293602,0.293602,-0.044425,0.044425,0.093176,-0.003648,-0.082972
parking,0.352980,0.139270,0.177496,0.045547,1.000000,-0.204433,0.204433,-0.037466,0.037466,-0.051497,0.051497,-0.067864,0.067864,-0.159173,0.159173,-0.091627,0.091627,0.131234,0.041327,-0.165705
mainroad_no,-0.288874,0.012033,-0.042398,-0.121706,-0.204433,1.000000,-1.000000,0.092337,-0.092337,0.044002,-0.044002,-0.011781,0.011781,0.105423,-0.105423,0.199876,-0.199876,-0.129971,-0.011450,0.133123
mainroad_yes,0.288874,-0.012033,0.042398,0.121706,0.204433,-1.000000,1.000000,-0.092337,0.092337,-0.044002,0.044002,0.011781,-0.011781,-0.105423,0.105423,-0.199876,0.199876,0.129971,0.011450,-0.133123
guestroom_no,-0.140297,-0.080549,-0.126469,-0.043538,-0.037466,0.092337,-0.092337,1.000000,-1.000000,0.372066,-0.372066,-0.010308,0.010308,0.138179,-0.138179,0.160897,-0.160897,-0.099721,-0.005821,0.099023
guestroom_yes,0.140297,0.080549,0.126469,0.043538,0.037466,-0.092337,0.092337,-1.000000,1.000000,-0.372066,0.372066,0.010308,-0.010308,-0.138179,0.138179,-0.160897,0.160897,0.099721,0.005821,-0.099023
basement_no,-0.047417,-0.097312,-0.102106,0.172394,-0.051497,0.044002,-0.044002,0.372066,-0.372066,1.000000,-1.000000,0.004385,-0.004385,0.047341,-0.047341,0.228083,-0.228083,-0.069852,-0.050284,0.117935
basement_yes,0.047417,0.097312,0.102106,-0.172394,0.051497,-0.044002,0.044002,-0.372066,0.372066,-1.000000,1.000000,-0.004385,0.004385,-0.047341,0.047341,-0.228083,0.228083,0.069852,0.050284,-0.117935
hotwaterheating_no,0.009229,-0.046049,-0.067159,-0.018847,-0.067864,-0.011781,0.011781,-0.010308,0.010308,0.004385,-0.004385,1.000000,-1.000000,-0.130023,0.130023,-0.059411,0.059411,0.008472,-0.063819,0.059194
hotwaterheating_yes,-0.009229,0.046049,0.067159,0.018847,0.067864,0.011781,-0.011781,0.010308,-0.010308,-0.004385,0.004385,-1.000000,1.000000,0.130023,-0.130023,0.059411,-0.059411,-0.008472,0.063819,-0.059194
airconditioning_no,-0.222393,-0.160603,-0.186915,-0.293602,-0.159173,0.105423,-0.105423,0.138179,-0.138179,0.047341,-0.047341,-0.130023,0.130023,1.000000,-1.000000,0.117382,-0.117382,-0.160994,0.053179,0.094086
airconditioning_yes,0.222393,0.160603,0.186915,0.293602,0.159173,-0.105423,0.105423,-0.138179,0.138179,-0.047341,0.047341,0.130023,-0.130023,-1.000000,1.000000,-0.117382,0.117382,0.160994,-0.053179,-0.094086
prefarea_no,-0.234779,-0.079023,-0.063472,-0.044425,-0.091627,0.199876,-0.199876,0.160897,-0.160897,0.228083,-0.228083,-0.059411,0.059411,0.117382,-0.117382,1.000000,-1.000000,-0.100249,0.011535,0.081271
prefarea_yes,0.234779,0.079023,0.063472,0.044425,0.091627,-0.199876,0.199876,-0.160897,0.160897,-0.228083,0.228083,0.059411,-0.059411,-0.117382,0.117382,-1.000000,1.000000,0.100249,-0.011535,-0.081271
furnishingstatus_furnished,0.145772,0.079054,0.108139,0.093176,0.131234,-0.129971,0.129971,-0.099721,0.099721,-0.069852,0.069852,0.008472,-0.008472,-0.160994,0.160994,-0.100249,0.100249,1.000000,-0.496748,-0.409462
furnishingstatus_semi-furnished,0.006156,0.050040,0.029834,-0.003648,0.041327,-0.011450,0.011450,-0.005821,0.005821,-0.050284,0.050284,-0.063819,0.063819,0.053179,-0.053179,0.011535,-0.011535,-0.496748,1.000000,-0.588405
furnishingstatus_unfurnished,-0.142278,-0.126252,-0.132107,-0.082972,-0.165705,0.133123,-0.133123,0.099023,-0.099023,0.117935,-0.117935,0.059194,-0.059194,0.094086,-0.094086,0.081271,-0.081271,-0.409462,-0.588405,1.000000

In [11]:
y = new_data.iloc[:,-1]
x = new_data.iloc[:,:-1]

In [12]:
x.shape

(545, 20)

In [13]:
y.shape

(545,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [15]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')
dtc.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [16]:
y_pred = dtc.predict(x_test)

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          C1       0.55      0.73      0.62        41
          C2       0.40      0.36      0.38        47
          C3       0.29      0.33      0.31        30
          C4       0.82      0.59      0.68        46

    accuracy                           0.51       164
   macro avg       0.52      0.50      0.50       164
weighted avg       0.54      0.51      0.51       164

In [18]:
from sklearn.metrics import precision_score
print(precision_score(y_test,y_pred,average="macro"))

0.515628978864273

In [19]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.5121951219512195

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc2 = DecisionTreeClassifier(criterion='entropy',max_depth=6,max_features=8 ,min_samples_split=2)

In [ ]:
cla