**Import Necessary Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

**Loading Dataset**

In [2]:
data = pd.read_csv('/content/Iris.csv')
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

**Data Cleaning**
 -> Checking for missing values

In [3]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

**Data Reduction**

Removing "Irrelevant" feature

In [4]:
data.drop(['Id'],axis=1,inplace=True)

**Data Integeration**

Merging all independent variables (features) into x and tranfering target / dependent variable into y

In [5]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

**Definition of tranining dataset**

Splitting data into training and testing method ( Hold Out)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

**Viewing Shape**

In [7]:
x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
61             5.9           3.0            4.2           1.5
92             5.8           2.6            4.0           1.2
112            6.8           3.0            5.5           2.1
2              4.7           3.2            1.3           0.2
141            6.9           3.1            5.1           2.3
..             ...           ...            ...           ...
9              4.9           3.1            1.5           0.1
103            6.3           2.9            5.6           1.8
67             5.8           2.7            4.1           1.0
117            7.7           3.8            6.7           2.2
47             4.6           3.2            1.4           0.2

[112 rows x 4 columns]

In [8]:
x_test.shape

(38, 4)

In [9]:
y_train.shape

(112,)

In [10]:
y_test.shape

(38,)

**Tranforming Data using Standard Scaler**

Standard scaler will convert data into z-score values.

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.56381749e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.86480506e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12644135e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31208072e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38312788e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -7.98707650e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31208072e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.85334584e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41411549e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.63981441e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.56381749e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
         7.41411549e-01],
       [-3.30414999e-01, -1.27067995e+00,  5.77759173e-02,
        -1.56991317e-01],
       [ 2.09056967e+00, -1.19254753e-01,  1.28501609e+00,
         1.38312788e+00],
       [ 4.76579890e-01,  5.71600368e-01,  5.04045072e-01,
         4.84725016e-01],
       [-4.45699984e-01, -1.50096499e+00,  1.99227301e-03,
        -1.56991317e-01],
       [ 4.76579890e-01, -8.10109874e-01,  6.15612361e-01,
         7.41411549e-01],
       [ 4.76579890e-01, -5.79824834e-01,  7.27179649e-01,
         3.56381749e-01],
       [-1.13740989e+00, -1.27067995e+00,  3.92477783e-01,
         6.13068282e-01],
       [ 4.76579890e-01, -1.27067995e+00,  6.71396005e-01,
         8.69754815e-01],
       [ 1.28357478e+00,  3.41315328e-01,  5.04045072e-01,
         2.28038483e-01],
       [ 7.07149859e-01, -1.19254753e-01,  7.82963294e-01,
         9.98098082e-01],
       [ 1.30724937e-01,  8.01885408e-01,  3.92477783e-01,
         4.84725016e-01],
       [-1.25269487e+00,  1.11030287e-01, -1.22524790e+00,
        -1.31208072e+00],
       [-9.98450310e-02, -8.10109874e-01,  7.27179649e-01,
         8.69754815e-01],
       [-3.30414999e-01, -8.10109874e-01,  2.25126850e-01,
         9.96952160e-02],
       [-3.30414999e-01, -3.49539793e-01, -1.09575016e-01,
         9.96952160e-02],
       [-4.45699984e-01, -1.27067995e+00,  1.13559562e-01,
         9.96952160e-02],
       [ 2.46009922e-01, -1.19254753e-01,  4.48261428e-01,
         2.28038483e-01],
       [ 1.51414475e+00,  3.41315328e-01,  1.22923245e+00,
         7.41411549e-01],
       [-6.76269952e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31208072e+00],
       [-1.82911979e+00, -1.19254753e-01, -1.50416612e+00,
        -1.44042398e+00],
       [ 5.91864874e-01, -8.10109874e-01,  8.38746938e-01,
         8.69754815e-01],
       [-2.15130015e-01, -1.19254753e-01,  2.25126850e-01,
        -2.86480506e-02],
       [-5.60984968e-01,  8.01885408e-01, -1.16946426e+00,
        -1.31208072e+00],
       [-2.15130015e-01,  3.10473581e+00, -1.28103155e+00,
        -1.05539418e+00],
       [ 1.16828980e+00,  1.11030287e-01,  6.15612361e-01,
         3.56381749e-01],
       [-1.48326484e+00,  1.11030287e-01, -1.28103155e+00,
        -1.31208072e+00],
       [ 1.54399532e-02, -1.19254753e-01,  7.27179649e-01,
         7.41411549e-01],
       [-9.06839920e-01, -1.27067995e+00, -4.44276882e-01,
        -1.56991317e-01],
       [-1.48326484e+00,  8.01885408e-01, -1.33681519e+00,
        -1.18373745e+00],
       [ 3.61294906e-01, -1.96153508e+00,  3.92477783e-01,
         3.56381749e-01],
       [ 1.51414475e+00,  1.26245549e+00,  1.28501609e+00,
         1.63981441e+00],
       [-2.15130015e-01, -3.49539793e-01,  2.25126850e-01,
         9.96952160e-02],
       [-1.25269487e+00, -1.19254753e-01, -1.33681519e+00,
        -1.44042398e+00],
       [ 1.39885976e+00, -1.19254753e-01,  1.17344880e+00,
         1.12644135e+00],
       [ 1.16828980e+00,  3.41315328e-01,  1.06188152e+00,
         1.38312788e+00],
       [ 7.07149859e-01, -1.19254753e-01,  1.11766516e+00,
         1.25478461e+00],
       [ 5.91864874e-01, -5.79824834e-01,  1.00609787e+00,
         1.12644135e+00],
       [-9.06839920e-01,  1.72302557e+00, -1.22524790e+00,
        -1.31208072e+00],
       [-1.25269487e+00,  8.01885408e-01, -1.22524790e+00,
        -1.31208072e+00],
       [ 7.07149859e-01,  3.41315328e-01,  7.27179649e-01,
         9.98098082e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.12644135e+00],
       [-1.59854983e+00, -1.73125004e+00, -1.39259884e+00,
        -1.18373745e+00],
       [ 3.61294906e-01,  8.01885408e-01,  8.94530582e-01,
         1.38312788e+00],
       [-1.13740989e+00, -1.19254753e-01, -1.33681519e+00,
        -1.31208072e+00],
       [-2.15130015e-01, -1.27067995e+00,  6.71396005e-01,
         9.98098082e-01],
       [ 1.16828980e+00,  1.11030287e-01,  8.94530582e-01,
         1.12644135e+00],
       [-1.71383481e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31208072e+00],
       [-1.02212490e+00,  1.26245549e+00, -1.33681519e+00,
        -1.31208072e+00],
       [ 1.51414475e+00, -1.19254753e-01,  1.11766516e+00,
         4.84725016e-01],
       [-9.06839920e-01,  1.03217045e+00, -1.33681519e+00,
        -1.18373745e+00],
       [-1.71383481e+00, -1.19254753e-01, -1.39259884e+00,
        -1.31208072e+00],
       [-5.60984968e-01,  1.95331061e+00, -1.16946426e+00,
        -1.05539418e+00],
       [-4.45699984e-01, -1.73125004e+00,  1.13559562e-01,
         9.96952160e-02],
       [ 1.05300481e+00,  3.41315328e-01,  1.17344880e+00,
         1.38312788e+00],
       [ 1.97528468e+00, -1.19254753e-01,  1.56393431e+00,
         1.12644135e+00],
       [-9.06839920e-01,  1.03217045e+00, -1.33681519e+00,
        -1.31208072e+00],
       [-1.13740989e+00,  1.11030287e-01, -1.28103155e+00,
        -1.44042398e+00],
       [-7.91554936e-01,  8.01885408e-01, -1.33681519e+00,
        -1.31208072e+00],
       [-2.15130015e-01, -5.79824834e-01,  3.92477783e-01,
         9.96952160e-02],
       [ 8.22434843e-01, -1.19254753e-01,  3.36694139e-01,
         2.28038483e-01],
       [-1.02212490e+00,  3.41315328e-01, -1.44838248e+00,
        -1.31208072e+00],
       [-9.06839920e-01,  5.71600368e-01, -1.16946426e+00,
        -9.27050916e-01],
       [ 5.91864874e-01, -3.49539793e-01,  2.80910495e-01,
         9.96952160e-02],
       [-5.60984968e-01,  8.01885408e-01, -1.28103155e+00,
        -1.05539418e+00],
       [ 2.09056967e+00, -1.04039491e+00,  1.73128525e+00,
         1.38312788e+00],
       [-1.13740989e+00, -1.50096499e+00, -2.76925949e-01,
        -2.85334584e-01],
       [ 2.32113964e+00,  1.72302557e+00,  1.45236703e+00,
         9.98098082e-01],
       [ 9.37719827e-01,  1.11030287e-01,  3.36694139e-01,
         2.28038483e-01],
       [-7.91554936e-01,  2.41388069e+00, -1.28103155e+00,
        -1.44042398e+00],
       [ 1.30724937e-01, -1.19254753e-01,  5.59828716e-01,
         7.41411549e-01],
       [-9.98450310e-02,  2.18359565e+00, -1.44838248e+00,
        -1.31208072e+00],
       [ 2.09056967e+00, -5.79824834e-01,  1.61971796e+00,
         9.98098082e-01],
       [-9.06839920e-01,  1.72302557e+00, -1.28103155e+00,
        -1.18373745e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.22524790e+00,
        -1.31208072e+00],
       [ 1.74471472e+00, -5.79824834e-01,  1.28501609e+00,
         8.69754815e-01],
       [-1.02212490e+00,  5.71600368e-01, -1.33681519e+00,
        -1.31208072e+00],
       [ 4.76579890e-01,  8.01885408e-01,  1.00609787e+00,
         1.51147115e+00],
       [-2.15130015e-01, -5.79824834e-01,  1.69343206e-01,
         9.96952160e-02],
       [-9.98450310e-02, -8.10109874e-01,  5.77759173e-02,
        -2.86480506e-02],
       [-2.15130015e-01, -1.04039491e+00, -1.65358660e-01,
        -2.85334584e-01],
       [ 5.91864874e-01,  3.41315328e-01,  8.38746938e-01,
         1.38312788e+00],
       [ 9.37719827e-01, -1.19254753e-01,  7.82963294e-01,
         1.38312788e+00],
       [ 4.76579890e-01, -1.27067995e+00,  6.15612361e-01,
         3.56381749e-01],
       [ 9.37719827e-01, -1.19254753e-01,  6.71396005e-01,
         6.13068282e-01],
       [-1.02212490e+00, -1.19254753e-01, -1.22524790e+00,
        -1.31208072e+00],
       [-4.45699984e-01, -1.50096499e+00, -5.37913713e-02,
        -2.85334584e-01],
       [ 9.37719827e-01,  1.11030287e-01,  1.00609787e+00,
         1.51147115e+00],
       [-9.98450310e-02, -8.10109874e-01,  7.27179649e-01,
         8.69754815e-01],
       [-9.06839920e-01,  8.01885408e-01, -1.28103155e+00,
        -1.31208072e+00],
       [ 8.22434843e-01, -3.49539793e-01,  4.48261428e-01,
         9.96952160e-02],
       [-3.30414999e-01, -1.19254753e-01,  1.69343206e-01,
         9.96952160e-02],
       [ 1.54399532e-02,  3.41315328e-01,  5.59828716e-01,
         7.41411549e-01],
       [ 4.76579890e-01, -1.73125004e+00,  3.36694139e-01,
         9.96952160e-02],
       [-4.45699984e-01,  1.03217045e+00, -1.39259884e+00,
        -1.31208072e+00],
       [-9.06839920e-01,  1.49274053e+00, -1.28103155e+00,
        -1.05539418e+00],
       [-1.13740989e+00,  1.11030287e-01, -1.28103155e+00,
        -1.44042398e+00],
       [ 4.76579890e-01, -3.49539793e-01,  1.00609787e+00,
         7.41411549e-01],
       [-9.98450310e-02, -8.10109874e-01,  1.69343206e-01,
        -2.85334584e-01],
       [ 2.09056967e+00,  1.72302557e+00,  1.61971796e+00,
         1.25478461e+00],
       [-1.48326484e+00,  3.41315328e-01, -1.33681519e+00,
        -1.31208072e+00]])

In [ ]:
x_test

array([[-0.09984503, -0.57982483,  0.72717965,  1.51147115],
       [ 0.13072494, -1.96153508,  0.11355956, -0.28533458],
       [-0.44569998,  2.64416573, -1.33681519, -1.31208072],
       [ 1.62942973, -0.34953979,  1.39658338,  0.74141155],
       [-1.0221249 ,  0.80188541, -1.28103155, -1.31208072],
       [ 0.47657989,  0.57160037,  1.22923245,  1.63981441],
       [-1.0221249 ,  1.03217045, -1.39259884, -1.18373745],
       [ 0.93771983,  0.11103029,  0.50404507,  0.35638175],
       [ 1.05300481, -0.57982483,  0.55982872,  0.22803848],
       [ 0.24600992, -0.57982483,  0.11355956,  0.09969522],
       [ 0.24600992, -1.04039491,  1.00609787,  0.22803848],
       [ 0.59186487,  0.34131533,  0.39247778,  0.35638175],
       [ 0.24600992, -0.57982483,  0.50404507, -0.02864805],
       [ 0.70714986, -0.57982483,  0.44826143,  0.35638175],
       [ 0.24600992, -0.34953979,  0.50404507,  0.22803848],
       [-1.13740989,  0.11103029, -1.28103155, -1.44042398],
       [ 0.13072494, -0.34953979,  0.39247778,  0.35638175],
       [-0.44569998, -1.04039491,  0.33669414, -0.02864805],
       [-1.25269487, -0.11925475, -1.33681519, -1.18373745],
       [-0.56098497,  1.95331061, -1.39259884, -1.05539418],
       [-0.330415  , -0.57982483,  0.61561236,  0.99809808],
       [-0.330415  , -0.11925475,  0.39247778,  0.35638175],
       [-1.25269487,  0.80188541, -1.05789697, -1.31208072],
       [-1.71383481, -0.34953979, -1.33681519, -1.31208072],
       [ 0.36129491, -0.57982483,  0.55982872,  0.74141155],
       [-1.48326484,  1.26245549, -1.55994977, -1.31208072],
       [-0.90683992,  1.72302557, -1.05789697, -1.05539418],
       [ 0.36129491, -0.34953979,  0.28091049,  0.09969522],
       [-1.0221249 , -1.73125004, -0.27692595, -0.28533458],
       [-1.0221249 ,  0.80188541, -1.2252479 , -1.05539418],
       [ 0.59186487,  0.11103029,  0.95031423,  0.74141155],
       [-0.56098497, -0.11925475,  0.39247778,  0.35638175],
       [-0.79155494,  1.03217045, -1.28103155, -1.31208072],
       [ 0.24600992, -0.11925475,  0.61561236,  0.74141155],
       [ 0.59186487, -0.57982483,  1.00609787,  1.25478461],
       [-0.79155494, -0.81010987,  0.05777592,  0.22803848],
       [-0.21513002,  1.72302557, -1.16946426, -1.18373745],
       [ 0.13072494, -0.81010987,  0.72717965,  0.48472502]])

**Naive Bayes Classifier (Gaussian NB)**



For more information:
https://scikit-learn.org/1.5/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB

In [11]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [14]:
# Predicting the Test set results
y_pred_gnb = classifier.predict(x_test)
#storing value in y_pred_gnb means y prediction of Guassian Naive Bayes classifier
#so that we can track variable and access output of specific classifier.

In [15]:
y_pred_gnb

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor'], dtype='<U15')

In [18]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_gnb = confusion_matrix(y_test, y_pred_gnb)

In [19]:
cm_gnb

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

**Viewing Attributes of Model**

In [27]:
print(classifier.classes_)
print(classifier.class_count_)
print(classifier.class_prior_)
#here we can see that in training
# Iris-setosa data is in 37 rows
# Iris-versicolor data is in 34 rows
# Iris-virginica data is in 41 rows

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[37. 34. 41.]
[0.33035714 0.30357143 0.36607143]

In [23]:
classifier.class_prior_
# prior probabilities of 3 classes

array([0.33035714, 0.30357143, 0.36607143])

**KNN - K Nearest Neighbour**

Importanat Parameters :
1. n_neighbors
2. weights
3. metric

Chnage above parameters and generate different models.

For More information :
https://scikit-learn.org/1.5/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors =10 , metric = 'euclidean', p = 2)
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=10)

In [31]:
y_pred_knn = knn_classifier.predict(x_test)
y_pred_knn

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [32]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_knn)

0.9736842105263158

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_knn))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        38
      macro avg       0.97      0.98      0.97        38
   weighted avg       0.98      0.97      0.97        38

In [35]:
from  sklearn.metrics import f1_score
f1_score(y_test,y_pred_knn,average='weighted')

0.9739522830846216

In [42]:
probability_values  = knn_classifier.predict_proba(x_test)
y_prediction_knn = knn_classifier.predict(x_test)
print("Comparison  of Probability values     |   Answer")
for i in range(len(probability_values)):
  print(probability_values[i],"|",y_prediction_knn[i])

#We can see whicherver probability is higher is predicted class label.

Comparison  of Probability values     |   Answer
[0.  0.1 0.9] | Iris-virginica
[0. 1. 0.] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[0. 0. 1.] | Iris-virginica
[1. 0. 0.] | Iris-setosa
[0. 0. 1.] | Iris-virginica
[1. 0. 0.] | Iris-setosa
[0.  0.9 0.1] | Iris-versicolor
[0.  0.8 0.2] | Iris-versicolor
[0. 1. 0.] | Iris-versicolor
[0.  0.1 0.9] | Iris-virginica
[0.  0.9 0.1] | Iris-versicolor
[0.  0.8 0.2] | Iris-versicolor
[0.  0.8 0.2] | Iris-versicolor
[0.  0.7 0.3] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[0.  0.9 0.1] | Iris-versicolor
[0. 1. 0.] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[1. 0. 0.] | Iris-setosa
[0.  0.3 0.7] | Iris-virginica
[0. 1. 0.] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[1. 0. 0.] | Iris-setosa
[0.  0.3 0.7] | Iris-virginica
[1. 0. 0.] | Iris-setosa
[1. 0. 0.] | Iris-setosa
[0. 1. 0.] | Iris-versicolor
[0. 1. 0.] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[0. 0. 1.] | Iris-virginica
[0. 1. 0.] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[0.  0.3 0.7] | Iris-virginica
[0. 0. 1.] | Iris-virginica
[0. 1. 0.] | Iris-versicolor
[1. 0. 0.] | Iris-setosa
[0.  0.1 0.9] | Iris-virginica

**Another Model (KNN)**

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier_2 = KNeighborsClassifier(n_neighbors =7 , metric = 'euclidean', p = 2)
knn_classifier_2.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=7)

In [37]:
y_pred_knn_2 = knn_classifier_2.predict(x_test)
y_pred_knn_2

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [38]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_knn_2)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_knn_2)

0.9736842105263158

In [40]:
from  sklearn.metrics import f1_score
f1_score(y_test,y_pred_knn_2,average='weighted')

0.9739522830846216

**Predict Probability**

In [ ]:
predict_proba

**SVM**

Importanat parameters:

1.kernel


For more information:
https://scikit-learn.org/1.5/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC

In [46]:
from sklearn.svm import SVC
svc_linear_kernel_model  = SVC(kernel = 'linear', random_state = 0)
svc_linear_kernel_model.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [47]:
y_pred_svc_linear = svc_linear_kernel_model.predict(x_test)
y_pred_svc_linear

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [48]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_svc_linear)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_svc_linear)

0.9736842105263158

In [50]:
from  sklearn.metrics import f1_score
f1_score(y_test,y_pred_svc_linear,average='weighted')

0.9739522830846216

**Different Model (SVM)**

Create different model by passing different arguments like:

kernel = 'poly' Or
kernel = 'sigmoid'  Or
kernel = 'rbf' (this is default arguemnt)

**Decision Tree Algorithm**

Importanat parameters :                                       
1. criterion
2. max_depth
3. min_samples_split

For more information:
https://scikit-learn.org/1.5/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier

In [51]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt_classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [52]:
y_pred_dt = dt_classifier.predict(x_test)
y_pred_dt

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [53]:
from sklearn.metrics import confusion_matrix
dt_cm = confusion_matrix(y_test, y_pred_dt)
dt_cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_dt)

0.9736842105263158

In [55]:
from  sklearn.metrics import f1_score
f1_score(y_test,y_pred_dt,average='weighted')

0.9739522830846216

**Random Forest Algorithm**

Important parameter :
1. n_estimators
2. criterion
3. max_depth
4. min_samples_split

For more information:
https://scikit-learn.org/1.5/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [56]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [57]:
rf_pred = rf_classifier.predict(x_test)
rf_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [58]:
from sklearn.metrics import confusion_matrix
rf_cm = confusion_matrix(y_test, rf_pred)
rf_cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  1,  8]])

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,rf_pred)

0.9473684210526315

In [60]:
from sklearn.metrics import f1_score
f1_score(y_test,rf_pred,average='weighted')

0.9473684210526315

**Logistic Algorithm**

For more information:https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LogisticRegression.html

In [61]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [62]:
lr_y_pred = lr_classifier.predict(x_test)
lr_y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [63]:
from sklearn.metrics import confusion_matrix
lr_cm = confusion_matrix(y_test, lr_y_pred)
lr_cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [64]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,lr_y_pred)

0.9736842105263158

In [65]:
from sklearn.metrics import f1_score
f1_score(y_test,lr_y_pred,average='weighted')

0.9739522830846216

**Hyper Parameter Tuning On Decision Tree**

In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# Define the hyperparameter  grid to explore
param_grid = {
    "criterion": [ "entropy"],
    "max_depth": [None, 5, 10, 15],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [5, int(np.sqrt(x_train.shape[1])), int(np.log2(x_train.shape[1]))]
}

# Create a decision tree classifier
dt = DecisionTreeClassifier()

# Create a GridSearchCV object
grid_search = GridSearchCV(dt, param_grid, cv=5, scoring="accuracy")

# Fit the GridSearchCV object to the training data
grid_search.fit(x_train, y_train)

# Get the best parameters and best score
best_params = grid_search.best_params_
#print(1)
best_score = grid_search.best_score_

print("Best Parameters:", best_params)

print("Best Score:", best_score)

Best Parameters: {'criterion': 'entropy', 'max_depth': None, 'max_features': 5, 'min_samples_leaf': 2, 'min_samples_split': 2}
Best Score: 0.9731225296442687

In [67]:
from sklearn.metrics import accuracy_score
#from sklearn.externals import joblib  # Import for saving the model

# Extract the best decision tree model
best_model = grid_search.best_estimator_
# Make predictions on the testing data
predictions = best_model.predict(x_test)

# Evaluate the performance of the model on the testing data
accuracy = accuracy_score(y_test, predictions)
print("Accuracy on testing data:", accuracy)
# Save the best model to a file (replace 'best_model.pkl' with your desired filename)
#joblib.dump(best_model, 'best_model.pkl')

Accuracy on testing data: 0.9473684210526315

**Real Time Testing of Classification Model**

In [68]:
best_model.predict([[5.0,3.6,1.4,0.2],[5.0,3.6,1.4,0.2],[5.0,3.6,1.4,0.2],[5.0,3.6,1.4,0.2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [69]:
best_model.predict([[5.0,3.6,1.4,0.2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)

In [70]:
best_model.predict(np.array([5.0,3.6,1.4,0.2]).reshape(1,-1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)

In [71]:
best_model.predict(np.array([5.0, 3.6, 1.4, 0.2]).reshape(1, -1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)

**If Transfomation is applied then**

In [ ]:
best_model.predict([[5.0,3.6,1.4,0.2],[5.0,3.6,1.4,0.2]])

array(['Iris-virginica', 'Iris-virginica'], dtype=object)

In [ ]:
best_model.predict(sc.transform([[5.0,3.6,1.4,0.2],[5.0,3.6,1.4,0.2]]))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array(['Iris-setosa', 'Iris-setosa'], dtype=object)

**Hyper Parameter Tuning On SVM**

In [72]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
			'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
			'kernel': ['rbf','sigmoid','linear','poly']}


grid_svm = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid_svm.fit(x_train, y_train)


# Get the best parameters and best score
best_params = grid_svm.best_params_
#print(1)
best_score = grid_svm.best_score_

print("Best Parameters:", best_params)

print("Best Score:", best_score)
# Make predictions on the testing data
best_model_svm = grid_svm.best_estimator_
predictions = best_model_svm.predict(x_test)

# Evaluate the performance of the model on the testing data
accuracy = accuracy_score(y_test, predictions)
print("Accuracy on testing data:", accuracy)
# Save the best model to a file (replace 'best_model.pkl' with your desired filename)
#joblib.dump(best_model, 'best_model.pkl')

Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.913 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=1, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.957 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.909 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.913 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.913 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.864 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.1, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.957 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.696 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.696 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.682 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.682 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.727 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.01, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.01, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.01, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.01, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.01, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.609 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.565 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.682 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.591 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.682 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.348 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.348 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.364 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.364 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.409 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.348 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.348 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.364 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.364 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.409 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.348 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.348 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.364 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.364 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.409 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.0001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.0001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.0001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.0001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.0001, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.0001, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.0001, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.0001, kernel=poly;, score=0.348 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.0001, kernel=poly;, score=0.348 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.0001, kernel=poly;, score=0.364 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.0001, kernel=poly;, score=0.364 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.0001, kernel=poly;, score=0.409 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.957 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.913 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END ......C=1, gamma=1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END ......C=1, gamma=1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END ......C=1, gamma=1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END ......C=1, gamma=1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END ......C=1, gamma=1, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END .........C=1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 2/5] END .........C=1, gamma=1, kernel=poly;, score=0.957 total time=   0.0s
[CV 3/5] END .........C=1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 4/5] END .........C=1, gamma=1, kernel=poly;, score=0.909 total time=   0.0s
[CV 5/5] END .........C=1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.957 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.1, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.957 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.913 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.913 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.909 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.696 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.696 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.682 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.682 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.727 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.826 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.826 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.955 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.818 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.696 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.696 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.682 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.682 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.727 total time=   0.0s
[CV 1/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.001, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.001, kernel=poly;, score=0.348 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.001, kernel=poly;, score=0.348 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.001, kernel=poly;, score=0.364 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.001, kernel=poly;, score=0.364 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=poly;, score=0.409 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.348 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.348 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.364 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.364 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.409 total time=   0.0s
[CV 1/5] END .C=1, gamma=0.0001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END .C=1, gamma=0.0001, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END .C=1, gamma=0.0001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END .C=1, gamma=0.0001, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END .C=1, gamma=0.0001, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END ..C=1, gamma=0.0001, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END ..C=1, gamma=0.0001, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.0001, kernel=poly;, score=0.348 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.0001, kernel=poly;, score=0.348 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.0001, kernel=poly;, score=0.364 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.0001, kernel=poly;, score=0.364 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.0001, kernel=poly;, score=0.409 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.957 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.957 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.864 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END .....C=10, gamma=1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END .....C=10, gamma=1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END .....C=10, gamma=1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END .....C=10, gamma=1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END .....C=10, gamma=1, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ......C=10, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END ......C=10, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ......C=10, gamma=1, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END ......C=10, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ........C=10, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 2/5] END ........C=10, gamma=1, kernel=poly;, score=0.957 total time=   0.0s
[CV 3/5] END ........C=10, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 4/5] END ........C=10, gamma=1, kernel=poly;, score=0.909 total time=   0.0s
[CV 5/5] END ........C=10, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.957 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.1, kernel=sigmoid;, score=0.348 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.1, kernel=sigmoid;, score=0.364 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.1, kernel=sigmoid;, score=0.409 total time=   0.0s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.909 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.913 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.913 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.909 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.957 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.909 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.955 total time=   0.0s
[CV 1/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.913 total time=   0.0s

**Cross Validation**

In [73]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

# Load your dataset
data = pd.read_csv("/content/Iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [74]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [75]:
data.drop(['Id'],axis=1,inplace=True)

In [76]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
# Split the data into features and target variable
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

# Split the data into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
model = DecisionTreeClassifier()


# Perform k-fold cross-validation with accuracy as the scoring metric
scores = cross_val_score(model, X_train, y_train, cv=5)
print(scores)
# Calculate the mean and standard deviation of the scores
mean_score = scores.mean()
std_score = scores.std()


print("Mean Accuracy:",mean_score)
print("Standard Deviation:", std_score)

[1.         1.         0.83333333 0.95833333 0.95833333]
Mean Accuracy: 0.95
Standard Deviation: 0.06123724356957944

In [77]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [79]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
# Split the data into features and target variable
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

# Split the data into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
model = DecisionTreeClassifier()


# Perform k-fold cross-validation with accuracy as the scoring metric
scores = cross_val_score(model, X_train, y_train, cv=5,scoring='accuracy')
print(scores)
# Calculate the mean and standard deviation of the scores
mean_score = scores.mean()
std_score = scores.std()


print("Mean Accuracy:",mean_score)
print("Standard Deviation:", std_score)

[0.95833333 1.         0.83333333 0.95833333 0.95833333]
Mean Accuracy: 0.9416666666666668
Standard Deviation: 0.05651941652604389

In [80]:
model.fit(X_train,y_train)
y_pred_k_fold_val = model.predict(X_test)
y_pred_k_fold_val

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

**K Fold Cross Validation**

In [81]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Split the data into features and target variable
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

# Split the data into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
model = DecisionTreeClassifier()

k = 5  # Number of folds
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform k-fold cross-validation with accuracy as the scoring metric
scores = cross_val_score(model, X_train, y_train, cv=kf, scoring='accuracy')
print(scores)
# Calculate the mean and standard deviation of the scores
mean_score = scores.mean()
std_score = scores.std()


print("Mean Accuracy:",mean_score)
print("Standard Deviation:", std_score)

[0.91666667 1.         0.91666667 0.83333333 1.        ]
Mean Accuracy: 0.9333333333333332
Standard Deviation: 0.06236095644623235

In [82]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [83]:

y_pred_k_fold_val = model.predict(X_test)
y_pred_k_fold_val

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_k_fold_val)
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [ ]:
from  sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_k_fold_val)

1.0

In [ ]:
from  sklearn.metrics import f1_score
f1_score(y_test,y_pred_k_fold_val,average='weighted')

1.0

**Pssible Values of Scroing Parameter in both (Grid Search CV , Cross Validation and K Fold Cross Validation)**

In [84]:
from sklearn import metrics
from sklearn.metrics._scorer import _SCORERS
_SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'd2_absolute_error_score', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])